### ISSUE TITLE
model_final.pth

### ISSUE THREAD

**Issue by kemalcanbora** [AnnaShtangey/Fashion-Detection-DeepFashion2-Detectron2-Flask#1]
Hi,
Can you share model_final.pth on google drive or something like that platforms ?

**Comment by AnnaShtangey** [comment]
Hi!
https://drive.google.com/drive/folders/19O4TUi0PDph4F8sMDNEDW4TVsbHXBiIO?usp=sharing

**Comment by kemalcanbora** [comment]
You're great!
